### ISSUE TITLE
"Data is malformed or incomplete" error for mm10

### ISSUE THREAD

**Issue by skannan4** [AllenWLynch/lisa#1]
Hi! I was trying to run Lisa for a mouse gene list of interest. I used the following line:

lisa oneshot mm10 c1_10.txt -b 3000 -c 1 --seed=2556 > results.tsv

However, this threw the following error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/skannan4/anaconda3/envs/lisa_env/lib/python3.8/site-packages/lisa/data/mm10/gene_locs.txt'

As indicated in the error, when I went to the specified folder, the only file was genes.tsv. (By contrast, the hg38 folder was filled with several relevant files - and the oneshot command worked when replacing mm10 with hg38).

I tried lisa download mm10 - this ran with no errors, but finished in maybe under 5 seconds, with no additional files downloaded (by contrast, it took ~20 minutes to download the files associated with hg38).

Is there something I need to do here to get the mouse data?

**Comment by liulab-dfci** [comment]
Hi Skannan, my testers were exclusively using human genes, so I haven't updated the mm10 data package to the newest version. I will be formatting the data today and it should be available early next week!

**Comment by liulab-dfci** [comment]
I have completed formatting the mm10 data. You should be able to download it using "lisa download mm10" in your LISA environment.

**Comment by skannan4** [comment]
Thanks, it worked! I'll go ahead and close this issue.
