### ISSUE TITLE
What's the difference between two formula

### ISSUE THREAD

**Issue by shangguandong1996** [AllenWLynch/lisa#4]
Hi, Allen

I noticed the formual of RP you posted in README
![图片](https://user-images.githubusercontent.com/22555126/123886388-e6bbad80-d981-11eb-9757-78bafa3be3de.png)

is different from the lisa origin paper 
![图片](https://user-images.githubusercontent.com/22555126/123886283-b411b500-d981-11eb-8d96-8b16eab83c45.png)

I am wondering whether there is a big difference between this two formula, or the former is more suitable for bam/bigwig file and latter is more suitable for peak-count file ?

Best wishes

Guandong Shang

**Comment by liulab-dfci** [comment]
Hi Shang,

This old formula was introduced in the paper and essentially specified an exponential decay, which we later simplified to the RP = 2^-(distance/L) since that is more conceptually simple but works essentially the same!

Allen

**Comment by shangguandong1996** [comment]
Thanks, allen. Thanks for your reply :). That's also I think
